name: netease-box
on:
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * 0'
  push:
    branches: main
jobs:
  updateTopTracks:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - name: Update Gist
        uses: ./
        env:
          GIST_ID: 3634718b3e28d97140c675edff9ca9dc
          ACCOUNT_ID: 1504809469
          SONG_TYPE: 1
          GH_TOKEN: ${{ secrets.GH_TOKEN }}